### ISSUE TITLE
Tag changes: basic paragraph formatting

### ISSUE THREAD

**Issue by teresaelsey** [BoboFraggins/typefi2bookxml#3]
- `<tps:p type="Normal">` is producing `<p align="center">` in the Introduction (`<supmatl>`); should produce `<p>`
- `<tps:p type="Normal">` is producing `<p align="left">` in the chapters (`<chapter>`); should produce `<p>`
- However, if the first paragraph of any new `<supmatl>`, `<chapter>`, or `<notes>` section is `<p>`, it should be changed to `<p align="left">` (the first paragraph of a new chapter is not indented). I don't see anything in the cXML to indicate this, so I think it must be being handled in the tool.

**Comment by BoboFraggins** [comment]
I took care of the first two parts of this ticket. Applying a class to the first <p> tag of those sections will come in the next batch of fixes.

**Comment by teresaelsey** [comment]
The second item seems to be fixed, but not the first -- `<tps:p type="Normal">` in the introduction of a book is still producing centered paragraphs (`<p align="center">`) when we want just `<p>`.

See the BLACK PRESIDENCY sample in Box. The introduction paragraphs are coming out centered.

**Comment by kmandaglio** [comment]
The first item seems to be fixed now, but not the third. The first `<tps:p type="Normal">` in the `<supmatl>` sections are becoming `<p align="left">`, but they are still only `<p>` in the `<chapter>` or `<notes>` sections.

**Comment by kmandaglio** [comment]
This is getting there, but still not quite. Only the first `<tps:p type="Normal">` tag should become `<p align="left">`, not just the first `<p>` of any type. For example, `<tps:p type="CN">`, `<tps:p type="CT">` and `<tps:p type="ET">` should be set in `<title></title>` tags.

**Comment by kmandaglio** [comment]
This looks good to me now!
